<nav class="navbar">
    <div class="nav_icon" id="nav-toggle">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="navbar__left">
        <h4 class="mt-2 ml-4"><a href="../home" class="text-decoration-none" style="color: #2e4a66;">欢喜食货</a></h4>
    </div>
    <div class="navbar__right">
        <a href="../admin">
            <img width="40" src="https://fnpphoto.cn/backend/avatar.jpg" alt="" style="border-radius: 50%;"/>
        </a>
    </div>
</nav>