#server:
#    port: 8080
#    servlet:
#        context-path: /
################# For 腾讯云 https #########################################
#server:
#    port: 443
#    ssl:
#        key-store: classpath:fishnprawn.cn.jks
#        key-store-password: 9j93756w87
#        key-store-type: JKS
#    servlet:
#        context-path: /

server:
    port: 443
    ssl:
        key-store: classpath:joynfish.com.jks
        key-store-password: 05d1h01i21d53he
        key-store-type: JKS
    servlet:
        context-path: /



spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/fishnprawn?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC&useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: Jaying.1996


        hikari:
            connection-init-sql: set names utf8mb4
        tomcat:
            init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
    jpa:
        properties:
            show-sql: true
            hibernate:
                ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5Dialect
    jmx:
        default-domain: joynfish

jasypt:
    encryptor:
        password: password

