<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <#assign path="${springMacroRequestContext.getContextPath()}">
    <link rel="stylesheet" type="text/css" href="${path}/css/index.css">
    <link rel="icon" href="${path}/img/favicon.png" type="image/png" sizes="16x16">
    <title>欢喜食货</title>
</head>
<body>
    <main class="main">
        <!-- title -->
        <section class="section section_main_title">
            <img class="favicon" src="${path}/img/favicon.png" alt="favicon">
            <h1 class="title">欢喜食货</h1>
        </section>

        <!-- 关于我们 -->
        <section class="section">
            <h3 class="section_title">公司介绍</h3>
            <p class="company_name">广州汇洋网络技术有限公司</p>
            <p>坐落于广东广州</p>
            <p>主营:软件和信息技术服务。</p>
            <p>一般经营：技术服务，技术开发，技术咨询，技术交流，技术转让，技术推广。信息咨询服务，互联网销售，网络技术服务。</p>
            <p>公司旗下有微信小程序“欢喜食货”，主要销售品种：深海鱼、浅海鱼、虾蟹类、贝壳类、干货类、熟制产品以及名贵干货
                甄选供应商，海港源头采购，没有中间商环节，为顾客提供新鲜和划算海鲜
                专业客服团队以及运营，为顾客提供更优质服务
            </p>
            <div class="bottom_border"></div>
        </section>

        <!-- 关于我们 -->
        <section class="section mt-30">
            <h3 class="section_title">关于我们</h3>
            <p>欢喜食货是一家新型互联网海鲜购物平台。用户足不出户，手机上随时随地搞定日常生活所需海鲜。</p>
            <p>欢喜希望能以创新的商业模式，高效的物流运输，以“上欢喜，买喜欢”为宗旨，做到真正让顾客喜欢的海鲜电商平台。以技术为核心驱动力，提升效率降低成本，以自营采购和甄选供应商保证食品安全，以更低价格为用户省时省钱打造极致体验，以可靠品质推动中国电商环境改善，同时推动中国食品安全进程和搭建海鲜食品安全标准体系，成为一家令社会尊敬、令顾客放心的优秀的互联网公司。</p>
            <p>欢喜目前处于创业发展阶段，总部设立于广东广州，创始团队核心成员均为互联网及零售领域的连续创业者和毕业于海外高等院校的留学海归。</p>
            <div class="bottom_border"></div>
        </section>

        <!-- 公司历程 -->
        <section class="section mt-30">
            <h3 class="section_title">公司历程</h3>
            <div class="history">
                <h5>2020.12 ------ 项目正式立项</h5>
                <h5>2021.06 ------ 天使轮融资</h5>
                <h5>2021.06 ------ 公司注册</h5>
                <h5>2021.08 ------ 小程序商城清爽上线</h5>
            </div>
            <div class="bottom_border"></div>
        </section>

        <!-- 公司创立 -->
        <section class="section mt-30" id="about">
            <h3 class="section_title">公司创立</h3>
            <div class="history">
                <h5>创立广州汇洋网络技术有限公司</h5>
                <h5>公司旗下有微信小程序“欢喜食货”。</h5>
                <h5>“欢喜食货”是一家新型互联网海鲜购物平台。用户足不出户，手机上随时随地搞定日常生活所需海鲜。</h5>
                <p>欢喜希望能以创新的商业模式，高效的物流运输，以“上欢喜，买喜欢”为宗旨，做到真正让顾客喜欢的海鲜电商平台。以技术为核心驱动力，提升效率降低成本，以自营采购和甄选供应商保证食品安全，以更低价格为用户省时省钱打造极致体验，以可靠品质推动中国电商环境改善，同时推动中国食品安全进程和搭建海鲜食品安全标准体系，成为一家令社会尊敬、令顾客放心的优秀的互联网公司。</p>
                <p>通过了解和对比我们能发现海鲜直送相对传统销售不仅仅在鲜度、速度上能将传统销售甩出好几条街，在价格上不用通过中间商就可以拿到第一手价格，在品质上，避开了繁琐的运输，直达客户手上，比传统销售保证产品新鲜。</p>
            </div>
            <div class="advantage">
                <h4>相对传统市场，我们会有什么优势</h4>
                <h5>先看看这张图表☟☟☟</h5>
                <img src="${path}/img/advantage.jpeg" alt="advantage">
            </div>
            <div class="bottom_border"></div>
        </section>

        <!-- 品牌特色 -->
        <section class="section mt-30">
            <h3 class="section_title">品牌特色</h3>
            <ul>
                <li>
                    <h4>产品</h4>
                    <p>产品是通过了解升级，不断从产品的保温、包装、源头潜心钻研，致力于带来第一手新鲜野生海鲜，确保客户收到的产品是优质的。</p>
                </li>
                <li>
                    <h4>服务</h4>
                    <p>有别于传统市场上无售后，我们团会不断更新最新的产品图片，为客户提供完整的下单教程，让每个消费者都能简单上手。同时我们有优秀的售前售后服务团队。</p>
                </li>
            </ul>
            <div class="bottom_border"></div>
        </section>

        <!-- 公司初衷 -->
        <section class="section ">
            <h3 class="section_title mt-30">公司初衷</h3>
            <div class="intention">
                <h5>足不出户想吃海鲜怎么办?</h5>
                <h5>市场海鲜担心不新鲜不正宗怎么办?</h5>
                <h5>超市找不到想吃的海鲜怎么办?</h5>
                <h5>为了打造与传统市场不一样的模式</h5>
                <h5>致力于把最新鲜的海鲜第一时间送达客户餐桌上</h5>
                <h5>于是创立了从码头渔船捕捞后，利用冷链配送直达送达客户手上的模式</h5>
            </div>

            <div class="bottom_border"></div>
        </section>

        <!-- 公司理念 -->
        <section class="section ">
            <h3 class="section_title mt-30">公司理念</h3>
            <div class="intention">
                <h5>这一切主要得益于快递的冷链输送</h5>
                <h5>国内大型冷链现在基本可实现全国隔天到达</h5>
                <h5>致力于让国内哪里的粉丝</h5>
                <h5>第一时间尝到新鲜的海味海鲜</h5>
                <h5>区别于市场上的海鲜参差不齐</h5>
                <h5>经常会有人工养殖的海鲜进入</h5>
                <h5>我们的海鲜保证都是野生捕捞</h5>
                <img src="${path}/img/fish1.jpg" alt="fish1" />
                <img src="${path}/img/fish2.jpg" alt="fish1" />
            </div>
            <div class="bottom_border"></div>
        </section>

        <!-- 联系我们 -->
        <section class="section section_contact mt-30">
            <div class="contact">
                <h3 class="contact_title">联系我们</h3>
                <p>电话: +86 13760799250</p>
                <p>邮箱: fnpapa@hotmail.com</p>
                <p>网址: www.joynfish.com/</p>
                <img class="qrcode" src="${path}/img/qrcode.jpg" alt="qrcode">
            </div>
            <div class="bottom_border_solid"></div>
        </section>

        <footer>
            <div class="footer_bottom">© 2022 Copyright:
                <a href="https://beian.miit.gov.cn/" style="color: white;"> 粤ICP备2021107781号</a>
            </div>
        </footer>
    </main>



</body>
</html>