<html>
<#include "../header/top.ftlh">
<link rel="stylesheet" type="text/css" href="${path}/css/success.css">
<body>

<div class="container">
    <div class="container1">
        <div class="wrapper1">
            <div class="loader1">
                <div class="dot1">
                </div>
            </div>
            <div class="loader1">
                <div class="dot1">
                </div>
            </div>
            <div class="loader1">
                <div class="dot1">
                </div>
            </div>
            <div class="loader1">
                <div class="dot1">
                </div>
            </div>
            <div class="loader1">
                <div class="dot1">
                </div>
            </div>
            <div class="loader1">
                <div class="dot1">
                </div>
            </div>
        </div>
        </h4><a href="${url}" class="text1 alert-link">The system will automatically jump after 1 seconds.</a>
    </div>
</div>
<script>
    setTimeout('location.href="${url}"', 1000);
</script>
</body>



